name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        uses: lannonbr/vsce-action@3.0.0
        with:
          args: "package -o ./english-copilot-${{ github.ref_name }}.vsix"

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./english-copilot-${{ github.ref_name }}.vsix